# Result type and others are implicitly dependent on std,
# so you need to compile Result type and others by yourself under no-std situation.
[unstable]
build-std = [
  "core",
  "compiler_builtins", # It's core's dependency.
  "alloc",
]
build-std-features = [
  # Enable compiler_builtin memcmp etc. to not use C built-in functions.
  "compiler-builtins-mem", #! need nightly 2019-09-30
]

[build]
target = "x86_64-blog_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner" # `runner` key is commands called during cargo run.
